#!/bin/zsh
set -euo pipefail
project_root="${0:A:h:h}"
configuration="${DIORAMA_BUILD_CONFIGURATION:-debug}"
export CLANG_MODULE_CACHE_PATH="$project_root/.build/module-cache"
export SWIFTPM_MODULECACHE_OVERRIDE="$CLANG_MODULE_CACHE_PATH"
mkdir -p "$CLANG_MODULE_CACHE_PATH"
swift build --package-path "$project_root" --configuration "$configuration"
bin_path="$(swift build --package-path "$project_root" --configuration "$configuration" --show-bin-path)"
app="$project_root/dist/Diorama.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$bin_path/Diorama" "$app/Contents/MacOS/Diorama"
cp "$project_root/Support/Info.plist" "$app/Contents/Info.plist"
cp "$project_root/Support/Diorama.icns" "$app/Contents/Resources/Diorama.icns"
identity="${DIORAMA_SIGNING_IDENTITY:--}"
codesign --force --options runtime --timestamp=none --sign "$identity" "$app"
"$project_root/scripts/verify-app.sh" "$app"
print "$app"
